### ISSUE TITLE
can't ope owl control OSX in 10.11.6

### ISSUE THREAD

**Issue by rvperez** [pingdynasty/OwlControl#9]
I try to install app but it gives me a can't open the aplication. I have permision fo download app from all places ( not restriction outside Mac Store outside)

**Comment by seppog** [comment]
In my case it was after updating to OSX 10.12.4 I had to open system preferences ->security -> there was an open owl.. said yes.. till update I have to do this for every "unsigned" app

**Comment by giuliomoro** [comment]
or right click on the package and click "open", then accept the successive security prompt.
